### ISSUE TITLE
HGVS output from oncotator MAF gives an error

### ISSUE THREAD

**Issue by inodb** [counsyl/hgvs#21]
I get the following error when reading data from the HGVS_coding_DNA_change column of oncotator MAF output (http://www.broadinstitute.org/oncotator/).

```
InvalidHGVSName: Invalid HGVS cDNA allele "5407-17T>-"
```

Not sure if this is an oncotator issue or a pyhgvs issue.

**Comment by mdrasmus** [comment]
This looks like an incorrect HGVS name. It seems to say `T` substituting to `-`, but `-` is not a valid nucleotide. Ideally, the name would be formatted as `TRANSCRIPT:c.5407-17delT`.

**Comment by inodb** [comment]
Thanks for the reply! Looks like an Oncotator issue then
