### ISSUE TITLE
parse_hgvs_name() crashes if start>end

### ISSUE THREAD

**Issue by rolfschr** [counsyl/hgvs#22]
I have trouble converting `chr19:g.10291325_10291323dup` (rs147441348) into chrom, pos, ref, alt using `parse_hgvs_name()`. The traceback is

```
Traceback (most recent call last):
  File "XXX", line 76, in main
    get_transcript=get_transcript)
  File "xxxx/pyhgvs/__init__.py", line 1360, in parse_hgvs_name
    chrom, start, end, ref, alt = get_vcf_allele(hgvs, genome, transcript)
  File "xxxx/pyhgvs/__init__.py", line 672, in get_vcf_allele
    alt = ref[0] + alt
IndexError: string index out of range
```

pyghvs is unable to retrieve the ref bases which is likely to be caused by `get_genomic_sequence()` which in turn does not support end coordinates bigger that start coordinates. Now, I am not sure this is wrong. However, I can paste `chr19:g.10291325_10291323dup` into Alamut in my case and find the variant. Exchanging start/end seems to yield the correct result, too.

**Comment by davmlaw** [comment]
I think this has been fixed, in the latest code, this errors with:

Invalid HGVS name: Coordinates are nonincreasing

**Comment by rolfschr** [comment]
Okay, thanks for the hint. I currently do not have pyhgvs at hand. Feel free to close this issue.

**Comment by naegelyd** [comment]
Confirmed this is fixed.
