### ISSUE TITLE
Need updated version of genes.refGene

### ISSUE THREAD

**Issue by NitinMandloi** [counsyl/hgvs#31]
Hi I ahve some variants in HGVS format which has NM_004364.4 transcript. 

This transcript is not there in pyhgvs/data/genes.refGene file.

Can you please tell me how can I get the updated file or add this to the file.

Thank you

Regards

**Comment by pkaleta** [comment]
The updated `genes.refGene` file can be downloaded from [UCSC table browser](https://genome.ucsc.edu/cgi-bin/hgTables).

**Comment by naegelyd** [comment]
Closing this given @pkaleta's link above. @NitinMandloi let me know if you are still having issues.
