### ISSUE TITLE
AttributeError: 'module' object has no attribute 'read_transcripts'

### ISSUE THREAD

**Issue by Sun-shan** [counsyl/hgvs#33]
Hello, I installed the 'hgvs', use:
pip install 'hgvs'
pip install 'pygr'

But there are some issues, how to fix it ?

[root@bio-x-2 hgvs]# python
Python 2.7.5 (default, Sep 15 2016, 22:37:39) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyhgvs as hgvs
>>> import hgvs.utils as hgvs_utils
>>> from pygr.seqdb import SequenceFileDB
>>> hgvs_utils.read_transcripts()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'read_transcripts'

**Comment by naegelyd** [comment]
@Sun-shan Does the following work for you?

```python
from pygr.seqdb import SequenceFileDB
from pyhgvs.utils import read_transcripts
read_transcripts()
```

**Comment by Sun-shan** [comment]
The command is as follows, is that OK?
[root@bio-x-2 ~]# python
Python 2.7.5 (default, Sep 15 2016, 22:37:39) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pygr.seqdb import SequenceFileDB
>>> from pyhgvs.utils import read_transcripts
>>> read_transcripts()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: read_transcripts() takes exactly 1 argument (0 given)

**Comment by naegelyd** [comment]
You need to pass `read_transcripts` the refgene file. So, you might do something like:

```python
from pyhgvs.utils import read_transcripts
with open('genes.refGene') as ref_gene_file:
    transcripts = read_transcripts(ref_gene_file)
```

We have more examples in the [example file](https://github.com/counsyl/hgvs/blob/master/examples/example1.py) which might help.

**Comment by Sun-shan** [comment]
Thank you very much, it works !
