### ISSUE TITLE
No module read_transcripts in hgvs_utils

### ISSUE THREAD

**Issue by jimhavrilla** [counsyl/hgvs#34]
My code is an exact copy of the README.md file on your site.  I can't get your package to work as directed.
    >>> import pyhgvs as hgvs
    >>> import hgvs.utils as hgvs_utils
    >>> hgvs_utils.read_transcripts
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    AttributeError: 'module' object has no attribute 'read_transcripts'

I am trying to use Ensembl transcripts as well, and the documentation is rather sparse on that.

**Comment by naegelyd** [comment]
@jimhavrilla Please see https://github.com/counsyl/hgvs/issues/33#issuecomment-285232646 to correct your issue. I will try to update the README to correct this problem.

**Comment by jimhavrilla** [comment]
In regards to the Ensembl transcripts, do I need to use the genePred created from the GRCh37 gtf generated by the UCSC binary in place of genes.refGene?

**Comment by naegelyd** [comment]
As long as the file you are reading transcripts from follows the format described [here](https://github.com/counsyl/hgvs/blob/master/pyhgvs/utils.py#L16-L35), you should be fine. If the file you have does not follow the [gene predictions extended format](http://genome.ucsc.edu/FAQ/FAQformat.html#GenePredExt), you may have issues getting `read_transcripts` to properly extract the information from the file.

**Comment by jimhavrilla** [comment]
It seems to follow the extended format, but does not have "0. uint
undocumented id" as specified here
<https://github.com/counsyl/hgvs/blob/master/pyhgvs/utils.py#L16-L35>

Jim Havrilla
PhD Candidate in Human Genetics, University of Utah
Accelerated BS/MS in Biomedical Engineering, Drexel University '12,
Concentration: Bioinformatics
*"Memory, comprehension, communication, motivation"*

**Comment by naegelyd** [comment]
We do not use the "undocumented id" field for anything in the `read_refgene` method however you would still want at least an empty value there in order to match for the required format. The reason you want an empty value is that we [split the row on tabs](https://github.com/counsyl/hgvs/blob/aebe5bd9683f4b5937fd653ce4b13fcd4f3ebb10/pyhgvs/utils.py#L41) so if you dropped the column altogether, you will probably have a bunch of off-by-one errors in your indexes when reading info from the row. Have you tried passing your file to `read_transcripts`? If so, does the returned data look sane? If not, it might be the result of the missing column I noted above.

**Comment by jimhavrilla** [comment]
Thanks I will try this.  If I have an issue I'll let you know.

Jim Havrilla
PhD Candidate in Human Genetics, University of Utah
Accelerated BS/MS in Biomedical Engineering, Drexel University '12,
Concentration: Bioinformatics
*"Memory, comprehension, communication, motivation"*

**Comment by jimhavrilla** [comment]
Not sure if it worked for me:
Running

    genome = SequenceFileDB('/scratch/ucgd/lustre/u1021864/serial/hg19.fasta')
    infile='Homo_sapiens.GRCh37.75.genePred'
    with open(infile) as reffile:
        transcripts=read_transcripts(reffile)
    def get_transcript(name):
        return transcripts.get(name)
    chrom, offset, ref, alt = hgvs.parse_hgvs_name('ENST00000155840:c.215A>G', genome, get_transcript=get_transcript)
I got
 
      File "getcoords.py", line 13, in <module>
        chrom, offset, ref, alt = hgvs.parse_hgvs_name('ENST00000155840:c.215A>G', genome, get_transcript=get_transcript)
      File "build/bdist.linux-x86_64/egg/pyhgvs/__init__.py", line 1356, in parse_hgvs_name
    ValueError: transcript is required

**Comment by jimhavrilla** [comment]
Is this because I didn't add the undocumented id field yet?

**Comment by jimhavrilla** [comment]
I added a 0 as a placeholder for the undocumented id field to each line of Homo_sapiens.GRCh37.75.genePred and that seemed to do the trick.  Thanks.

**Comment by jimhavrilla** [comment]
Also for anyone who has other issues with Ensembl transcripts, make sure bsddb3 is installed and that the fasta "chr" header is not there if your genePred file has its chromosomes without that header.
