### ISSUE TITLE
Running UTA locally

### ISSUE THREAD

**Issue by leoSeattle** [counsyl/hgvs#38]
hi, I preferred to run UTA locally, and I have downloaded and installed the docker and the postgreSQL docker. But "docker" technology is quite new to me, and I am not sure how to run the database. Could you help me on this? Thanks

**Comment by lacek** [comment]
@leoSeattle I think you were working on https://github.com/biocommons/hgvs?

**Comment by davmlaw** [comment]
Wrong repo - please close this comment
