### ISSUE TITLE
README.md (import hgvs error)

### ISSUE THREAD

**Issue by LouisGil** [counsyl/hgvs#48]
Noticed that the code in the UI's readme didnt work for me it looks like I was resolved in the examples1.py file. In the second line use 

import pyhgvs.utils as hgvs_utils
intstead of 
import hgvs.utils as hgvs_utils

**Comment by naegelyd** [comment]
The example script had an issue but it was in referencing `Genome` instead of `Fasta` after moving to pyfaidx. Confirmed script can be run in https://github.com/counsyl/hgvs/pull/55 after moving to `Fasta`. The import looks correct and the script runs without issue on that PR.
